require("lazy").setup({
	{ import = "plugins.ui" },
	--	{ import = "plugins.neocodium" },
	--	{ import = "plugins.dashboard" },
	{ import = "plugins.markdown" },
	{ import = "plugins.multicursor" },
	{ import = "plugins.treesitter" },
	{ import = "plugins.mason" },
	{ import = "plugins.completion" },
	{ import = "plugins.lsp" },
	{ import = "plugins.formatting" },
	{ import = "plugins.lint" },
	{ import = "plugins.git" },
	{ import = "plugins.statusline" },
	{ import = "plugins.dap" },
	{ import = "plugins.autopairs" },
	{ import = "plugins.trouble" },
	{ import = "plugins.surround" },
})
